### ISSUE TITLE
15.10.2019 5. Einheit

### ISSUE THREAD

**Issue by TimUntersberger** [gkoe/leoiot20#2]
- Vielleicht eigenes Repo?
- Passen Issues zum Ausmachen von Treffen?
- EspWifiManager fix
- https problem
- Sollen wir es möglich machen, dass man mit unseren OTA Server mehrere Firmwares abspeichert? 
- Brauchen 2 mehr esps, damit wir beide parallel an dem mesh netzwerk arbeiten können. Momentan müssen wir liveshare von vscode nehmen damit wir "parallel" arbeiten
- Wer ist der User "dagreiyo"
- Stütz zum Repo hinzufügen

Bitte einen Kommentar schreiben damit wir uns sicher sein können, dass jeder dieses Issue gesehen hat.

**Comment by StefanWaldl** [comment]
gesehen

**Comment by TimUntersberger** [comment]
gesehen :)

**Comment by TimUntersberger** [comment]
* OTA mehrere Apps supporten
  * in der config gibts sowos wie "app_name"
