### ISSUE TITLE
OTA Improvements

### ISSUE THREAD

**Issue by TimUntersberger** [gkoe/leoiot20#3]
* Firmware Verwaltungs UI (Jeder Firmware einen Namen zuweisen)
* Device Overview (wenn esp neue firmware downloaded -> in einer lokalen db updaten)
  * Man sieht welches Device welche Firmware oben hat
* Schützen mit einem Passwort

Sollen wir diese Sachen implementieren?

**Comment by gkoe** [comment]
Besprechen wir morgen!
