### ISSUE TITLE
PlatformIO mit der esp-idf cli ersetzen 

### ISSUE THREAD

**Issue by TimUntersberger** [gkoe/leoiot20#6]
Wir haben heute gesehen, dass es ein cli tool von ESP-IDF selber gibt, welche einiges mehr kann als PlatformIO.

Deswegen überlegen wir, ob wir auf die cli von esp-idf umsteigen sollen, weil mit der cli platformio unnötig ist.

**Comment by StefanWaldl** [comment]
Zwei Esps funktionieren nicht

**Comment by gkoe** [comment]
Ich nehme morgen zwei weitere ESPs vom letzten Samstag mit. Bin von 8:00 Uhr - 10:00 Uhr in der 4AHIF
